Models/Favorites.cs
using System.ComponentModel.DataAnnotations;

namespace DevDiary.Models
{
    public class Favorites
    {
        public int Id { get; set; }
        public int BlogPostId { get; set; }


        [Required]
        public string? AppUserId { get; set; }

        public virtual BlogPost? BlogPost { get; set; }
        public virtual AppUser? AppUser { get; set; }
    }
}

Controllers/BlogPostsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DevDiary.Data;
using DevDiary.Models;
using DevDiary.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using X.PagedList;
using DevDiary.Helpers;

namespace DevDiary.Controllers
{
    // [Authorize]
    public class BlogPostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IImageService _imageService;
        private readonly IBlogService _blogService;


        public BlogPostsController(ApplicationDbContext context, IImageService imageService, IBlogService blogService)
        {
            _context = context;
            _imageService = imageService;
            _blogService = blogService;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AuthorArea(int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;


            IPagedList<BlogPost> blogPosts = await (await _blogService.GetAllBlogPostAsync())
                .OrderByDescending(b => b.Created) // Ordenar por fecha de creación
                .ToPagedListAsync(page, pageSize);

            return View(blogPosts);
        }

        public IActionResult AboutMe()
        {
            return PartialView("AboutMe");
        }

        // GET: BlogPosts
        [AllowAnonymous]
        public async Task<IActionResult> Index(int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;         

            // Recupera los Blog Posts ordenados por fecha de creación descendente (los más recientes primero)
            var blogPosts = await _blogService.GetBlogPostAsync();

            // Aplica un filtro para excluir los blogs eliminados
            blogPosts = blogPosts.Where(post => !post.IsDeleted);

            blogPosts = blogPosts.OrderByDescending(post => post.Created);


            // Pagina los resultados
            //IPagedList<BlogPost> pagedBlogPosts = blogPosts.ToPagedList(page, pageSize);
            IPagedList<BlogPost> pagedBlogPosts = await blogPosts.ToPagedListAsync(page, pageSize);

            ViewData["ActionName"] = nameof(Index);

            return View(pagedBlogPosts);
        }

        public async Task<IActionResult> SearchIndex(string? searchString, int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await _blogService.SearchBlogPosts(searchString).ToPagedListAsync(page, pageSize);


            ViewData["ActionName"] = nameof(SearchIndex);
            ViewData["SearchString"] = searchString;

            return View(nameof(Index), blogPosts);
        }

        public async Task<IActionResult> Popular(int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await (await _blogService.GetPopularBlogPostAsync()).ToPagedListAsync(page, pageSize);

            // Calcula el número de orden basándote en la página y el índice en esa página
            for (int i = 0; i < blogPosts.Count; i++)
            {
                int orderNumber = (page - 1) * pageSize + i + 1;
                blogPosts[i].Order = orderNumber;
            }
         
            // Llamada a la vista parcial y pasando el modelo (blogPosts)
            return PartialView("_MostPopularBlogsPartial", blogPosts);
        }


        public async Task<IActionResult> Category(int? pageNum, string categoryName)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;

            IPagedList<BlogPost> blogPosts = await (await _blogService.GetBlogPostByCategoryAsync(categoryName))
                .ToPagedListAsync(page, pageSize);

            ViewData["CategoryName"] = categoryName;
          

            return View("Index", blogPosts);
        }

        public async Task<IActionResult> Favorites(int? pageNum)
        {
            int pageSize = 3;
            int page = pageNum ?? 1;
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            IEnumerable<BlogPost> likedPosts = await _blogService.GetFavoriteBlogPostsAsync(userId);
            IPagedList<BlogPost> blogPosts = await likedPosts.ToPagedListAsync(page, pageSize);

            ViewData["ActionName"] = nameof(Favorites);

            // Calcula el número de orden basándote en la página y el índice en esa página
            for (int i = 0; i < blogPosts.Count; i++)
            {
                int orderNumber = (page - 1) * pageSize + i + 1;
                blogPosts[i].Order = orderNumber;
            }

            return View(blogPosts);
        }


        // GET: BlogPosts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string? slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            BlogPost? blogPost = await _context.BlogPosts
                .Include(b => b.Tags)  // Asegúrate de incluir las etiquetas aquí
                .Include(l => l.Likes)
                .Include(c => c.Comments)
                .Include(bc => bc.Category)
                .FirstOrDefaultAsync(bp => bp.Slug == slug);

      

            if (blogPost == null)
            {
                return NotFound();
            }

            // Agrega este código para manejar la imagen
            if (blogPost.ImageData != null && blogPost.ImageType != null)
            {
                blogPost.ImageFileString = $"data:{blogPost.ImageType};base64,{Convert.ToBase64String(blogPost.ImageData)}";
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            BlogPost blogPost = new BlogPost();
            blogPost.ImageData = null; // Inicializa la imagen como nula
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name"); // Aquí lo tienes
            return View(blogPost);
        }


        // POST: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Abstract,Content,IsPublished,CategoryId, ImageFile")] BlogPost blogPost, string? stringTags)
        {
            ModelState.Remove("Slug");

            if (ModelState.IsValid)
            {
                // Static class StringHelper
                string? newSlug = StringHelper.BlogPostSlug(blogPost.Title);

                if (!await _blogService.ValidSlugAsync(newSlug, blogPost.Id))
                {
                    // Handle invalid slug
                    ModelState.AddModelError("Title", "A similar Title/Slug is already in use.");

                    ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
                    return View(blogPost);
                }

                // Handle valid slug
                blogPost.Slug = newSlug;
                blogPost.Created = DateTime.Now;


                //Set the Image data if one has been chosen
                if (blogPost.ImageFile != null)
                {
                    blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.ImageFile);
                    blogPost.ImageType = blogPost.ImageFile.ContentType;
                }

                // Use the blog service
                await _blogService.AddBlogPostAsync(blogPost);

                if (string.IsNullOrEmpty(stringTags) == false)
                {
                    IEnumerable<string> tags = stringTags.Split(',');
                    await _blogService.AddTagsToBlogPostAsync(tags, blogPost.Id);
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryId"] = new SelectList(_context.Set<Category>(), "Id", "Name", blogPost.CategoryId);
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BlogPosts == null)
            {
                return NotFound();
            }

            BlogPost? blogPost = await _context.BlogPosts.Include(bp => bp.Tags)  // Incluir las etiquetas
                                                .Include(bp => bp.Category)
                                                .FirstOrDefaultAsync(bp => bp.Id == id);

            if (blogPost == null)
            {

                return NotFound();
            }

            ViewData["CategoryId"] = new SelectList(_context.Set<Category>(), "Id", "Name", blogPost.CategoryId);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Abstract,Content,Created,Slug,IsPublished,IsDeleted,ImageFile,ImageData,ImageType,CategoryId")] BlogPost blogPost)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    blogPost.Created = DateTime.Now;

                    //Set the Image data if one has been chosen
                    if (blogPost.ImageFile != null)
                    {

                        blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.ImageFile);

Views/Shared/Favorites.cshtml
@model IPagedList<BlogPost>
@using DevDiary.Enums;
@using DevDiary.Services
@using DevDiary.Services.Interfaces;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@using X.PagedList;
@inject IImageService _ImageService





<!-- Start Trending Post Area  -->
<div class="axil-trending-post-area axil-section-gap bg-color-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2 class="title">Favorites</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">



                <!-- Start Axil Tab Content  -->
                <div class="tab-content">

                    <!-- Single Tab Content  -->

                    <div class="row trend-tab-content tab-pane fade show active" id="trendone" role="tabpanel" aria-labelledby="trend-one">
                        <div class="col-lg-8">
                            <!-- Start Single Post  -->
                            @foreach (BlogPost blogPost in Model)
                            {
                                <div class="content-block trend-post post-order-list axil-control">
                                    <div class="post-inner">
                                        <span class="post-order-list">@blogPost.Order.ToString("D2")</span>
                                        <div class="post-content">
                                            <div class="post-cat">
                                                <div class="post-cat-list">
                                                    <a class="hover-flip-item-wrapper" href="#">
                                                        <span class="hover-flip-item">
                                                            <span data-text="@blogPost.Category?.Name">@blogPost.Category?.Name</span>
                                                        </span>
                                                    </a>
                                                </div>
                                            </div>
                                            <h3 class="title">
                                                <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost.Slug">
                                                    @blogPost.Title
                                                </a>
                                            </h3>
                                            <div class="post-meta-wrapper">
                                                <div class="post-meta">
                                                    <div class="content">
                                                        <h6 class="post-author-name">
                                                            <a class="hover-flip-item-wrapper" href="#">
                                                                <span class="hover-flip-item">
                                                                    <span data-text="Gelson Hernandez">Gelson Hernandez</span>
                                                                </span>
                                                            </a>
                                                        </h6>
                                                        <ul class="post-meta-list">
                                                            <li>@blogPost.Created.ToString("MMM dd, yyyy")</li>
                                                            <li>@blogPost.Likes.Count @((blogPost.Likes.Count == 1) ? "like" : "likes")</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <ul class="social-share-transparent justify-content-end">
                                                    <li><a href="https://www.facebook.com/gelsonhs"><i class="fab fa-facebook-f"></i></a></li>
                                                    <li><a href="https://www.instagram.com/gelsonhz/"><i class="fab fa-instagram"></i></a></li>
                                                    <li><a href="https://twitter.com/gelsonhz"><i class="fab fa-twitter"></i></a></li>
                                                    <li><a href="https://www.linkedin.com/in/gelson-hernandez/"><i class="fab fa-linkedin-in"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="post-thumbnail">
                                        <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost?.Slug">
                                            <img src="@(blogPost.ImageData != null ? _ImageService.ConvertByteArrayToFile(blogPost.ImageData, blogPost.ImageType, DefaultImage.BlogPostImage) : "/img/Default-Image.png")" alt="Post Images">
                                        </a>
                                    </div>
                                </div>
                            }
                            <!-- End Single Post  -->

                        </div>
                    </div>

                </div>
                <!-- End Axil Tab Content  -->
                <div>
                    <div>
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    </div>
                    @Html.PagedListPager(Model, pageNum => Url.Action("Popular", new { pageNum }),
                             new PagedListRenderOptions
                    {
                        LiElementClasses = new string[] { "my-page-item" },
                        PageClasses = new string[] { "my-page-link" }
                    })
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Trending Post Area  -->

Views/Shared/_AuthorAreaPartial.cshtml
<div class="axil-author-area axil-author-banner bg-color-grey">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about-author">
                    <div class="media">
                        <div class="thumbnail">
                            <a href="#">
                                <img src="~/assets/images/post-images/author/Gelson3.jpg" alt="Author
                                                    Images" style="height: 100px; width: 100px; border-radius: 50%;
                                                    object-fit: cover;">
                            </a>
                        </div>
                        <div class="media-body">
                            <div class="author-info">
                                <h1 class="title"><a href="#">Gelson Hernandez</a></h1>
                                <span class="b3 subtitle">Software Developer</span>
                            </div>
                            <div class="content">
                                <p class="b1 description">

                                    “As a software developer, I delve into the labyrinth of complexity,
                                    finding joy in animating code and harnessing technology for meaningful impact.
                                    This blog serves as my stage to share insights, lend support to fellow developers on
                                    their coding odysseys,
                                    and foster a sense of community. Together, let’s embark on an exhilarating journey
                                    through the dynamic realm of programming!”
                                </p>
                                <ul class="social-share-transparent size-md">
                                    <li><a href="https://www.facebook.com/gelsonhs"><i
                                                class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="https://www.instagram.com/gelsonhz/"><i
                                                class="fab fa-instagram"></i></a></li>
                                    <li><a href="https://twitter.com/gelsonhz"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="mailto:gelsonhz@outlook.com"><i class="far fa-envelope"></i></a></li>
                                    <li><a href="https://www.linkedin.com/in/gelson-hernandez/"><i
                                                class="fab fa-linkedin-in"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_BlogCardPartial.cshtml
@model BlogPost
@using DevDiary.Enums;
@using DevDiary.Services.Interfaces;
@inject IImageService _ImageService






 <div class="content-block post-list-view mt--30">
    <div class="post-thumbnail">
        <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model?.Slug">
            <img src="@(Model.ImageData != null ? _ImageService.ConvertByteArrayToFile(Model.ImageData, Model.ImageType, DefaultImage.BlogPostImage) : "/img/Default-Image.png")" alt="Post Images">
        </a>
    </div>

    <div class="post-content">
        <div class="post-cat">
            <div class="post-cat-list">
                <a class="hover-flip-item-wrapper" href="#">
                    <span class="hover-flip-item">
                        <span data-text="@Model?.Category?.Name">@Model?.Category?.Name</span>
                    </span>

                </a>
            </div>
        </div>
        <h4 class="title">
            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model?.Slug">
                @Model?.Title
            </a>
        </h4>
        <div class="post-meta-wrapper">
           @*  @if (ViewContext.RouteData.Values["action"]?.ToString() == "Category")
            {
                <div class="category-title">
                    Category: @ViewData["CategoryName"]
                </div>
            } *@
            <div class="post-meta">
                <div class="content">
                    <h6 class="post-author-name">
                        <a class="hover-flip-item-wrapper" href="#">
                            <span class="hover-flip-item">
                                <span data-text="Gelson Hernandez">Gelson Hernandez</span>
                            </span>
                        </a>
                    </h6>
                    <ul class="post-meta-list">
                        <li>@Model?.Created.ToString("MMM dd, yyyy")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div> 

Views/Shared/_LogoutPartial.cshtml
<form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "BlogPosts", new { area = "" })">
</form>

Views/Shared/_MostPopularBlogsPartial.cshtml
@model IPagedList<BlogPost>
@using DevDiary.Enums;
@using DevDiary.Services
@using DevDiary.Services.Interfaces;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;
@using X.PagedList;
@inject IImageService _ImageService

@{
    Layout = "_Layout";
}


<!-- Start Trending Post Area  -->
<div class="axil-trending-post-area axil-section-gap bg-color-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2 class="title">Most Popular</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">



                <!-- Start Axil Tab Content  -->
                <div class="tab-content">

                    <!-- Single Tab Content  -->

                    <div class="row trend-tab-content tab-pane fade show active" id="trendone" role="tabpanel" aria-labelledby="trend-one">
                        <div class="col-lg-8">
                            <!-- Start Single Post  -->
                            @foreach (BlogPost blogPost in Model)
                            {
                                <div class="content-block trend-post post-order-list axil-control">
                                    <div class="post-inner">
                                        <span class="post-order-list">@blogPost.Order.ToString("D2")</span>
                                        <div class="post-content">
                                            <div class="post-cat">
                                                <div class="post-cat-list">
                                                    <a class="hover-flip-item-wrapper" href="#">
                                                        <span class="hover-flip-item">
                                                            <span data-text="@blogPost.Category?.Name">@blogPost.Category?.Name</span>
                                                        </span>
                                                    </a>
                                                </div>
                                            </div>
                                            <h3 class="title">
                                                <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost.Slug">
                                                    @blogPost.Title
                                                </a>
                                            </h3>
                                            <div class="post-meta-wrapper">
                                                <div class="post-meta">
                                                    <div class="content">
                                                        <h6 class="post-author-name">
                                                            <a class="hover-flip-item-wrapper" href="#">
                                                                <span class="hover-flip-item">
                                                                    <span data-text="Gelson Hernandez">Gelson Hernandez</span>
                                                                </span>
                                                            </a>
                                                        </h6>
                                                        <ul class="post-meta-list">
                                                            <li>@blogPost.Created.ToString("MMM dd, yyyy")</li>
                                                            <li>@blogPost.Likes.Count @((blogPost.Likes.Count == 1) ? "like" : "likes")</li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <ul class="social-share-transparent justify-content-end">
                                                    <li><a href="https://www.facebook.com/gelsonhs"><i class="fab fa-facebook-f"></i></a></li>
                                                    <li><a href="https://www.instagram.com/gelsonhz/"><i class="fab fa-instagram"></i></a></li>
                                                    <li><a href="https://twitter.com/gelsonhz"><i class="fab fa-twitter"></i></a></li>
                                                    <li><a href="https://www.linkedin.com/in/gelson-hernandez/"><i class="fab fa-linkedin-in"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="post-thumbnail">
                                        <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost?.Slug">
                                            <img src="@(blogPost.ImageData != null ? _ImageService.ConvertByteArrayToFile(blogPost.ImageData, blogPost.ImageType, DefaultImage.BlogPostImage) : "/img/Default-Image.png")" alt="Post Images">
                                        </a>
                                    </div>
                                </div>
                            }
                            <!-- End Single Post  -->

                        </div>
                    </div>

                </div>
                <!-- End Axil Tab Content  -->
                <div>
                    <div>
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    </div>
                    @Html.PagedListPager(Model, pageNum => Url.Action("Popular", new { pageNum }),
                             new PagedListRenderOptions
                    {
                        LiElementClasses = new string[] { "my-page-item" },
                        PageClasses = new string[] { "my-page-link" }
                    })
                </div>

                
            </div>
        </div>
    </div>
</div>
<!-- End Trending Post Area  -->

Views/Shared/_SideBarPartial.cshtml
@using DevDiary.Enums;
@using DevDiary.Services;
@using DevDiary.Services.Interfaces;
@using X.PagedList;
@inject IImageService _ImageService
@inject IBlogService BlogService


@{
    int pageSize = 3;
    int page = 1;
    if (int.TryParse(Context.Request.Query["pageNum"].FirstOrDefault(), out int pageNum))
    {
        page = pageNum;
    }
    IPagedList<BlogPost> blogPosts = (await BlogService.GetPopularBlogPostAsync()).ToPagedList(page, pageSize);
}


<div class="col-lg-4 col-xl-4 mt_md--40 mt_sm--40">
    <div class="sidebar-inner">

        <!-- Start Single Widget  -->
      @*   <div class="axil-single-widget widget widget_categories mb--30">
            <ul>
                @foreach (Category category in await BlogService.GetCategoriesAsync())
                {
                    <li class="cat-item">
                        <a href="/BlogPosts/Category/@category.Id" class="inner">
                            <div class="thumbnail">
                                <img src="@_ImageService.ConvertByteArrayToFile(
                            category.ImageData, category.ImageType, DefaultImage.CategoryImage)"
                                     alt="@category.Name">
                            </div>
                            <div class="content">
                                <h5 class="title">@category.Name</h5>
                            </div>
                        </a>
                    </li>
                }

            </ul>

        </div> *@
        <!-- End Single Widget  -->
        <!-- Start Single Widget  -->
        <div class="axil-single-widget widget widget_search mb--30">
            <h5 class="widget-title">Search</h5>
            <form asp-action="SearchIndex" asp-controller="BlogPosts">
                <div class="axil-search form-group">
                    <button type="submit" class="search-button"><i class="fal fa-search"></i></button>
                    <input type="text" class="form-control" placeholder="Search" name="searchString">
                </div>
            </form>
        </div>
        <!-- End Single Widget  -->
        <!-- Start Single Widget  -->
        <div class="axil-single-widget widget widget_postlist mb--30">
            <h5 class="widget-title">Popular on Blogar</h5>
            <!-- Start Post List  -->
            <div class="post-medium-block">
                @foreach (BlogPost blogPost in await BlogService.GetPopularBlogPostAsync(3))
                {
                    <!-- Start Single Post  -->
                    <div class="content-block post-medium mb--20">
                        <div class="post-thumbnail">
                            <a href="post-details.html">
                                <img src="@(blogPost.ImageData != null ? _ImageService.ConvertByteArrayToFile(blogPost.ImageData, blogPost.ImageType, DefaultImage.BlogPostImage) : "/img/Default-Image.png")" alt="Post Images">
                            </a>
                        </div>
                        <div class="post-content">
                            <h6 class="title">
                                <a asp-controller="BlogPosts" asp-action="Details" asp-route-slug="@blogPost.Slug">
                                    @blogPost.Title
                                </a>
                            </h6>

                            <div class="post-meta">
                                <ul class="post-meta-list">
                                    <li>@blogPost.Created.ToString("MMM dd, yyyy")</li>
                                    <li>@blogPost.Likes.Count @((blogPost.Likes.Count == 1) ? "like" : "likes")</li>

                                </ul>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <!-- End Single Widget  -->

    </div>
</div>